import { Resend } from 'resend'
import { NextResponse } from 'next/server'

export async function POST(request: Request) {
  try {
    // Check if RESEND_API_KEY is set
    if (!process.env.RESEND_API_KEY) {
      console.log('RESEND_API_KEY not configured - skipping email')
      return NextResponse.json({ message: 'Email service not configured' }, { status: 200 })
    }

    const resend = new Resend(process.env.RESEND_API_KEY)
    const { title, description } = await request.json()

    const { data, error } = await resend.emails.send({
      from: 'iSPY <onboarding@resend.dev>',
      to: ['graceshao203@gmail.com'],
      subject: `[ALERT] ${title}`,
      html: `
        <h2>${title}</h2>
        <p>${description}</p>
        <p><em>This alert was generated by iSPY's real-time monitoring system.</em></p>
      `
    })
    
    if (error) {
      console.error('Resend API error:', error)
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({ data })
  } catch (error) {
    console.error('Email error:', error)
    return NextResponse.json({ error: error instanceof Error ? error.message : 'Unknown error' }, { status: 500 })
  }
}
